### ISSUE TITLE
Video clips of DGE functionality

### ISSUE THREAD

**Issue by mgravitt** [hashed-io/document-graph-book#2]
Video clip(s) of creating, editing, extending, encrypting, and IPFS. 

- It can use voice over or text on screen.
- It can be multiple clips or all in one clip.
- Should we use Loom? YouTube?
- In addition, save files as mp4 and upload to IPFS.

**Comment by AugustoLara** [comment]
Encryption: https://www.veed.io/view/f1e6a2ff-5be6-4fb6-b888-26f82d266542
Edit & Extend: https://www.veed.io/view/e6871274-8c75-49e7-8320-47e6534005b8
Create: https://www.veed.io/view/7ac52596-5a6d-4055-94ba-7f7c6ba0bb21
IPFS: https://www.veed.io/view/a6035cfd-6ba0-42a8-bd50-02f668ca8eec

**Comment by AugustoLara** [comment]
Videos ready and moving them to the documentation
