### ISSUE TITLE
Final edit pass of the `document-graph-book`

### ISSUE THREAD

**Issue by mgravitt** [hashed-io/document-graph-book#3]
Clean up the existing documentation, better screenshots of DGE, adjust the flow as necessary.

Polish introduction a bit, etc.

**Comment by garcia-alejandro** [comment]
The changes are in the `page/getting-started` branch
1.- 4e242126e08f4c0d9d479f030ee20275b959f9a8
2.- 4e242126e08f4c0d9d479f030ee20275b959f9a8
3.- 3735d92d82dc1868993884b21d50ffda94b62024
